#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "civicrm_drupal"
name = "CiviCRM on Drupal"
description.en = "CRM for non-profits, NGOs and advocacy organizations"
description.fr = "CRM pour organisations à but non lucratif et ONG"

version = "5.80.0~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://civicrm.org"
demo = "https://civicrm.org/demo"
admindoc = "https://docs.civicrm.org/"
userdoc = "https://docs.civicrm.org/"
code = "https://github.com/civicrm/civicrm-drupal-8"
cpe = "cpe:2.3:a:civicrm:civicrm"
fund = "https://civicrm.org/civicrm/contribute/transact?reset=1&id=47"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/drupal"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.install_profil]
    ask.en = "Choose the Drupal install profile to use"
    ask.fr = "Choisissez le profile d'installation de Drupal"
    type = "select"
    choices = ["minimal", "standard"]
    default = "standard"

[resources]

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.2-fpm",
        "php8.2-cli",
        "php8.2-gd",
        "php8.2-mysql",
        "php8.2-xml",
        "php8.2-ldap",
        "php8.2-mbstring",
        "php8.2-json",
        "php8.2-simplexml",
        "php8.2-curl",
        "php8.2-soap",
        "php8.2-intl",
        "php8.2-zip",
        "php8.2-readline",
        "php8.2-bcmath",
        "php8.2-mbstring",
        "php8.2-fileinfo",
        "php8.2-soap",
        "curl",
        "libzip-dev",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
