#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.install_profil = "standard"
    args.language = "fr"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.c72c8bf3487e8295ce4216fccb40e8b2f0d6c690.name = "Upgrade from 2024.12.10~ynh1"
